### ISSUE TITLE
underlying JCB project

### ISSUE THREAD

**Issue by marcodings** [joomla-projects/com_release_checking#1]
Please add underlying JCB project to facilitate maintenance at the source

**Comment by marcodings** [comment]
I was referring to the JCB project itself to be added here, not the content of readme

**Comment by Llewellynvdm** [comment]
The JCB package is already available public in JCB package area under the community packages.
![image](https://user-images.githubusercontent.com/5607939/101800199-b0b5f980-3b15-11eb-8733-4f580631f820.png)

The [actual package location](https://github.com/vdm-io/JCB-Community-Packages/blob/master/JCB_trackReleaseChecking.zip) is in the JCB [community packages repo](https://github.com/vdm-io/JCB-Community-Packages).
